from __future__ import annotations

from doc.wire_models import Ping, PingRequest

from zeared.doc import (
    build_docs,
    document,
    introspect_message,
    is_message_class,
    render_message,
)


class TestIsMessageClass:
    def test_message_recognised(self):
        assert is_message_class(Ping)

    def test_plain_payload_is_not_a_message(self):
        assert not is_message_class(PingRequest)


class TestIntrospectMessage:
    def setup_method(self):
        self.md = introspect_message(Ping)

    def test_topic_and_category(self):
        assert self.md.topic == 'rio/command/ping/{source}/{reader_id}'
        assert self.md.category == 'command'

    def test_wire_metadata(self):
        assert self.md.schema_version == '2'
        assert self.md.encoding == 'msgpack'
        assert self.md.retained is False
        assert self.md.dedupe is True
        assert self.md.request is PingRequest

    def test_slots_flag_inherited_field(self):
        # `source` is inherited from _CmdBase; `reader_id` is declared here.
        assert [(s.name, s.is_field) for s in self.md.slots] == [
            ('source', True), ('reader_id', True),
        ]


class TestRenderMessage:
    def setup_method(self):
        self.md = render_message(Ping)

    def test_badge_and_topic(self):
        assert self.md.startswith('# Ping')
        assert '`command` · schema `2`' in self.md
        assert '## Topic' in self.md
        assert '`rio/command/ping/{source}/{reader_id}`' in self.md
        assert '| `source` | yes |' in self.md

    def test_wire_line_and_request_link(self):
        assert 'Encoding `msgpack`' in self.md
        assert 'Retained `no`' in self.md
        assert 'Retention TTL `∞`' in self.md
        assert 'Request [`PingRequest`](PingRequest.md)' in self.md

    def test_reuses_seared_sections(self):
        assert '## Fields' in self.md
        assert '`note`' in self.md
        assert 'Generated by `zeared.doc`' in self.md

    def test_rst_cleaned_inherited(self):
        assert ':class:' not in self.md


class TestPlainFallback:
    def test_non_message_has_no_topic(self):
        md = document(PingRequest)
        assert '## Topic' not in md
        assert '## Fields' in md


class TestBuildDocsDispatch:
    def setup_method(self):
        self.docs = build_docs('doc.wire_models')

    def test_dispatch_and_exclusion(self):
        assert 'Ping.md' in self.docs
        assert 'PingRequest.md' in self.docs
        assert '_CmdBase.md' not in self.docs
        assert 'index.md' in self.docs

    def test_message_is_wire_aware_plain_is_not(self):
        assert '## Topic' in self.docs['Ping.md']
        assert '## Topic' not in self.docs['PingRequest.md']
