"""Tests for the TypeScript emitter (``zeared.doc.typescript``)."""
from __future__ import annotations

from zeared.doc.typescript import emit, generate, main, ts_type

from doc.ts_models import Spectrum


def _field(cls, attr):
    for a, _wire, f in cls.__seared_fields__:
        if a == attr:
            return f
    raise KeyError(attr)


class TestTsType:
    def test_scalars(self):
        assert ts_type(_field(Spectrum, 'id')) == 'number'
        assert ts_type(_field(Spectrum, 'name')) == 'string'
        assert ts_type(_field(Spectrum, 'flag')) == 'boolean'
        assert ts_type(_field(Spectrum, 'blob')) == 'string'      # bytes → base64

    def test_decimal_as_number_vs_string(self):
        assert ts_type(_field(Spectrum, 'price')) == 'number'     # as_number=True
        assert ts_type(_field(Spectrum, 'label')) == 'string'     # default form

    def test_many_and_keyed(self):
        assert ts_type(_field(Spectrum, 'tags')) == 'string[]'
        assert ts_type(_field(Spectrum, 'counts')) == 'Record<string, number>'

    def test_tuple(self):
        assert ts_type(_field(Spectrum, 'pair')) == '[number, string]'

    def test_enum_reference(self):
        assert ts_type(_field(Spectrum, 'band')) == 'Band'
        assert ts_type(_field(Spectrum, 'mode')) == 'Mode'

    def test_nested_reference(self):
        assert ts_type(_field(Spectrum, 'inner')) == 'Inner'

    def test_union_nested_envelope(self):
        t = ts_type(_field(Spectrum, 'action'))
        assert t == (
            '{ type: "start"; args: StartArgs } | '
            '{ type: "stop"; args: StopArgs }'
        )

    def test_union_flat_envelope(self):
        assert ts_type(_field(Spectrum, 'kind')) == '(FlatA & { kind: "a" })'


class TestEmit:
    def setup_method(self):
        self.ts = generate('doc.ts_models')

    def test_optionality_and_nullability(self):
        assert '  id: number;' in self.ts            # required
        assert '  count?: number;' in self.ts        # optional, non-null default
        assert '  ratio?: number | null;' in self.ts  # nullable

    def test_enum_aliases_emitted(self):
        assert 'export type Band = 0 | 1;' in self.ts
        assert 'export type Mode = "fast" | "slow";' in self.ts

    def test_wire_key_rename_and_quoting(self):
        assert '  wireName: string;' in self.ts      # data_key rename
        assert '  "x-ray": string;' in self.ts       # non-identifier key quoted
        assert 'renamed' not in self.ts              # attr name not leaked

    def test_field_jsdoc(self):
        assert '/** a documented field */' in self.ts

    def test_dump_false_field_excluded(self):
        assert 'internal' not in self.ts

    def test_reference_closure_complete(self):
        for name in ('FlatA', 'Inner', 'StartArgs', 'StopArgs'):
            assert f'export interface {name} {{' in self.ts

    def test_message_jsdoc_wire_contract(self):
        assert '@topic rio/telemetry/spectrum/{id}' in self.ts
        assert '@schemaVersion 3' in self.ts
        assert '@encoding msgpack' in self.ts

    def test_deterministic(self):
        assert generate('doc.ts_models') == self.ts

    def test_header_present(self):
        assert self.ts.startswith('// Generated by `python -m zeared.doc.typescript`')


class TestRequestClosure:
    def test_request_payload_pulled_in(self):
        # PingRequest is reachable only via Ping.REQUEST (not a field ref).
        ts = generate('doc.wire_models')
        assert 'export interface PingRequest {' in ts
        assert 'export interface Ping {' in ts

    def test_inherited_slot_field_included(self):
        ts = generate('doc.wire_models')
        # `source` is inherited from the private base and is a template slot.
        assert '  source: string;' in ts
        assert '  note?: string | null;' in ts

    def test_private_base_excluded(self):
        ts = generate('doc.wire_models')
        assert 'interface _CmdBase' not in ts


class TestEmitDirect:
    def test_emit_expands_closure_from_single_class(self):
        # Passing only [Spectrum] still pulls its references + enums.
        ts = emit([Spectrum])
        assert 'export interface Inner {' in ts
        assert 'export type Band' in ts


class TestCli:
    def test_stdout(self, capsys):
        rc = main(['doc.ts_models'])
        assert rc == 0
        assert 'export interface Spectrum {' in capsys.readouterr().out

    def test_output_file(self, tmp_path):
        out = tmp_path / 'types.ts'
        rc = main(['doc.ts_models', '-o', str(out)])
        assert rc == 0
        assert 'export interface Spectrum {' in out.read_text()

    def test_check_passes_when_current(self, tmp_path):
        out = tmp_path / 'types.ts'
        main(['doc.ts_models', '-o', str(out)])
        assert main(['doc.ts_models', '-o', str(out), '--check']) == 0

    def test_check_fails_when_stale(self, tmp_path):
        out = tmp_path / 'types.ts'
        out.write_text('// stale\n')
        assert main(['doc.ts_models', '-o', str(out), '--check']) == 1

    def test_check_fails_when_missing(self, tmp_path):
        out = tmp_path / 'nope.ts'
        assert main(['doc.ts_models', '-o', str(out), '--check']) == 1
