"""Markdown rendering for a :class:`MessageDoc`.

Prepends the topic + wire-contract preamble, then reuses seared's field / enum
/ variant section renderers so the two layers stay in lockstep.
"""
from __future__ import annotations

from typing import Callable

from seared.doc import render_enums, render_fields_table, render_variants

from .introspect import MessageDoc, introspect_message

LinkFor = Callable[[type], str]


def _default_link(cls: type) -> str:
    return f'{cls.__name__}.md'


def _yn(value: bool) -> str:
    return 'yes' if value else 'no'


def render_topic(md: MessageDoc) -> str:
    if not md.topic:
        return ''
    out = ['## Topic', '', f'`{md.topic}`']
    for extra in md.extra_topics:
        out.append(f'`{extra}` (extra)')
    if md.slots:
        out += ['', '| slot | payload field? |', '|------|----------------|']
        for slot in md.slots:
            out.append(f'| `{slot.name}` | {_yn(slot.is_field)} |')
    return '\n'.join(out)


def render_wire(md: MessageDoc, link_for: LinkFor = _default_link) -> str:
    ttl = '∞' if md.retention_ttl is None else f'{md.retention_ttl}s'
    bits = [
        f'Encoding `{md.encoding}`',
        f'Retained `{_yn(md.retained)}`',
        f'Liveliness `{_yn(md.liveliness)}`',
        f'Dedupe `{_yn(md.dedupe)}`',
        f'Retention TTL `{ttl}`',
    ]
    if md.request is not None:
        bits.append(f'Request [`{md.request.__name__}`]({link_for(md.request)})')
    return ' · '.join(bits)


def render_message(cls: type, link_for: LinkFor = _default_link) -> str:
    """Render the full wire-aware Markdown page for a ``@zeared`` Message."""
    md = introspect_message(cls)
    s = md.schema

    header = f'# {s.name}'
    badge = []
    if md.category:
        badge.append(f'`{md.category}`')
    if md.schema_version:
        badge.append(f'schema `{md.schema_version}`')
    if badge:
        header += '\n\n' + ' · '.join(badge)
    if s.doc:
        header += '\n\n' + s.doc

    sections = [
        header,
        render_topic(md),
        render_wire(md, link_for),
        render_fields_table(s, link_for),
        render_enums(s),
        render_variants(s, link_for),
        '_Generated by `zeared.doc` — do not edit by hand._',
    ]
    return '\n\n'.join(sec for sec in sections if sec) + '\n'
