"""TypeScript type generation for ``@zeared`` message classes.

A renderer over the same introspection substrate as the Markdown docs: it
reuses ``seared.doc``'s discovery / reference-closure pipeline
(:func:`seared.doc.collect`) but maps each raw seared ``Field`` straight to a
TypeScript type for full fidelity (unions, tuples, ``Decimal(as_number)``),
rather than round-tripping through the display-oriented ``FieldDoc``.

Output is a single ``.ts`` module of ``export interface`` / ``export type``
declarations — the shape a browser consumer sees after a bridge decodes a
zeared message to JSON. **zeared ships types only**: the mesh→websocket bridge
(auth, identity scope, transport) is the consumer's to build. See the emitted
header for the exact wire-shape contract these types assume.

CLI: ``python -m zeared.doc.typescript <module-or-package> [-o out.ts] [--check]``.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

from seared.doc import collect

from .introspect import introspect_message, is_message_class

if TYPE_CHECKING:
    from enum import Enum

    from seared import Seared

# Strip Sphinx/RST role prefixes so docstrings read as plain JSDoc text:
# ``:class:`Ping``` → ```Ping```. Mirrors ``seared.doc``'s cleaning.
_RST_ROLE = re.compile(r':[\w.]+:(`[^`]+`)')

# Scalar seared Field class name → TS type. Types describe the JSON wire form
# a bridge emits. ``Bytes``/``NDArray`` are base64 / structured under JSON;
# frames aren't browser-portable — the consumer decides, so they map to
# ``unknown`` rather than a false-precise shape.
_SCALAR: dict[str, str] = {
    'Bool': 'boolean',
    'Int': 'number',
    'Float': 'number',
    'Str': 'string',
    'UUID': 'string',
    'Path': 'string',
    'Date': 'string',
    'DateTime': 'string',
    'Time': 'string',
    'TimeDelta': 'string',
    'Bytes': 'string',  # base64 on the JSON wire
    'Dict': 'Record<string, unknown>',
    'NDArray': 'unknown',
    'PandasFrame': 'unknown',
    'PolarsFrame': 'unknown',
}

_HEADER = """\
// Generated by `python -m zeared.doc.typescript` — do not edit by hand.
//
// These types describe the JSON wire form of zeared messages, as a bridge
// would hand them to a browser. Contract assumed:
//   - Keys are wire keys (a field's `data_key` when set, else its name).
//   - Fields declared on the class are present; template-slot fields that
//     are also declared fields are included (a decoder merges them from the
//     key). Capture-only slots (in the key, not declared) are routing
//     metadata and are NOT part of these types.
//   - `Bytes` is base64-encoded on the JSON wire; frames/ndarrays are left
//     as `unknown` — decode them in the bridge if you need them.
//   - Optional (`?`) marks a field the sender may omit (it has a default).
//     `| null` marks a nullable field (declared `X | None`).
"""


def _ts_literal(value: Any) -> str:
    """Render an enum wire value as a TS literal."""
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'


def _key_token(key: str) -> str:
    """Quote a wire key that isn't a bare JS identifier."""
    if key.isidentifier():
        return key
    return '"' + key.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _union_type(f: Any) -> str:
    """Discriminated-union TS type for a seared ``Union`` field."""
    tag_key = _key_token(getattr(f, 'tag_key', 'type'))
    payload_key = getattr(f, 'payload_key', None)
    parts: list[str] = []
    for tag, cls in f.variants.items():
        name = cls.__name__
        tag_lit = _ts_literal(tag)
        if payload_key is None:
            # Flat: variant fields sit beside the tag.
            parts.append(f'({name} & {{ {tag_key}: {tag_lit} }})')
        else:
            pk = _key_token(payload_key)
            parts.append(f'{{ {tag_key}: {tag_lit}; {pk}: {name} }}')
    return ' | '.join(parts) if parts else 'unknown'


def ts_type(f: Any) -> str:
    """Map a raw seared ``Field`` to a TypeScript type expression."""
    if getattr(f, 'enum', None) is not None:
        base = f.enum.__name__
    elif hasattr(f, 'variants') and getattr(f, 'variants', None):
        base = _union_type(f)
    elif getattr(f, 'schema', None) is not None:
        base = f.schema.__name__  # nested T(schema)
    elif hasattr(f, 'tuple_fields'):
        base = '[' + ', '.join(ts_type(sub) for sub in f.tuple_fields) + ']'
    elif type(f).__name__ == 'Decimal':
        base = 'number' if getattr(f, 'as_number', False) else 'string'
    elif getattr(type(f), 'TS_TYPE', None):
        # A custom field class names its own TS type (and may ship the alias
        # that defines it via ``TS_PRELUDE`` — see ``_collect_preludes``).
        base = str(type(f).TS_TYPE)
    else:
        base = _SCALAR.get(type(f).__name__, 'unknown')
    if getattr(f, 'keyed', False):
        return f'Record<string, {base}>'
    if getattr(f, 'many', False):
        # Parenthesise union element types so `A | B[]` binds correctly.
        return f'({base})[]' if '|' in base else f'{base}[]'
    return base


def _member(attr: str, wire_key: str, f: Any) -> list[str]:  # noqa: ARG001  (attr kept for call-site symmetry)
    """Emit the interface member line(s) for one field (with JSDoc)."""
    required = bool(f.required)
    has_factory = getattr(f, 'default_factory', None) is not None
    default_val = getattr(f, 'missing', None)
    nullable = (not required) and (not has_factory) and (default_val is None)

    key = _key_token(wire_key)
    opt = '' if required else '?'
    tp = ts_type(f)
    if nullable:
        tp = f'{tp} | null'

    lines: list[str] = []
    doc = getattr(f, 'doc', None)
    if doc:
        lines.append(f'  /** {doc.strip()} */')
    lines.append(f'  {key}{opt}: {tp};')
    return lines


def _real_docstring(cls: type[Seared]) -> str:
    """The class's own docstring, or '' if it is the generated one.

    The class's own docstring, or '' if it's the dataclass-generated signature
    (``Name(field: T = ...)``) that stands in when none was written.
    """
    doc = (cls.__doc__ or '').strip()
    if not doc or doc.startswith(f'{cls.__name__}('):
        return ''
    return doc


def _interface_jsdoc(cls: type[Seared]) -> list[str]:
    """Leading JSDoc block for an interface — wire contract for a Message."""
    lines: list[str] = []
    doc = _real_docstring(cls).splitlines()
    summary = _RST_ROLE.sub(r'\1', doc[0].strip()) if doc else ''
    body: list[str] = []
    if summary:
        body.append(summary)
    if is_message_class(cls):
        md = introspect_message(cls)
        body.append(f'@topic {md.topic}' if md.topic else '')
        body.extend(f'@extraTopic {extra}' for extra in md.extra_topics)
        if md.schema_version is not None:
            body.append(f'@schemaVersion {md.schema_version}')
        body.append(f'@encoding {md.encoding}')
    body = [b for b in body if b]
    if not body:
        return lines
    lines.append('/**')
    lines.extend(f' * {b}' for b in body)
    lines.append(' */')
    return lines


def render_interface(cls: type[Seared]) -> str:
    """Render one ``export interface`` for a seared/message class."""
    out: list[str] = []
    out.extend(_interface_jsdoc(cls))
    out.append(f'export interface {cls.__name__} {{')
    members = [
        line
        for attr, wire, f in cls.__seared_fields__
        if getattr(f, 'dump', True)  # skip load-only fields
        for line in _member(attr, wire, f)
    ]
    if members:
        out.extend(members)
    out.append('}')
    return '\n'.join(out)


def _collect_enums(classes: list[type[Seared]]) -> list[type[Enum]]:
    """Gather every Enum class referenced by any field, deduped by identity."""
    seen: dict[int, type[Enum]] = {}
    for cls in classes:
        for _attr, _wire, f in cls.__seared_fields__:
            e = getattr(f, 'enum', None)
            if e is not None and id(e) not in seen:
                seen[id(e)] = e
    return sorted(seen.values(), key=lambda e: e.__name__)


def _collect_preludes(classes: list[type[Seared]]) -> list[str]:
    """Gather every custom field class's ``TS_PRELUDE`` (a type alias its ``TS_TYPE`` needs), deduped.

    A downstream package can subclass a seared field (a branded string, say) and declare
    ``TS_TYPE = 'SecretRef'`` plus ``TS_PRELUDE = 'export type SecretRef = string & {...};'``;
    the alias is emitted once, before the interfaces, whenever such a field is in play.
    """
    seen: dict[str, None] = {}
    for cls in classes:
        for _attr, _wire, f in cls.__seared_fields__:
            prelude = getattr(type(f), 'TS_PRELUDE', None)
            if prelude:
                seen.setdefault(str(prelude).strip(), None)
    return sorted(seen)


def render_enum(enum_cls: type[Enum]) -> str:
    """Render an Enum as a TS union-of-literals type alias (wire values)."""
    literals = ' | '.join(_ts_literal(m.value) for m in enum_cls)
    return f'export type {enum_cls.__name__} = {literals};'


def _expand(classes: list[type[Seared]]) -> list[type[Seared]]:
    """Full set of classes to emit, including referenced ones.

    Full set to emit: every input class plus the transitive closure of its field
    references (nested ``T`` targets, ``Union`` variants) and its ``REQUEST`` payload
    closure. Deduped, then sorted ``(module, name)`` so output is deterministic
    regardless of input order (stable ``--check``).
    """
    from seared.doc import introspect as _introspect

    found: dict[int, type[Seared]] = {}

    def walk(c: type[Seared]) -> None:
        if id(c) in found or not getattr(c, '__seared_fields__', None):
            return
        found[id(c)] = c
        for ref in _introspect(c).references:
            walk(ref)
        req = getattr(c, 'REQUEST', None)  # not a field ref — pull it in
        if req is not None:
            walk(req)

    for cls in classes:
        walk(cls)
    return sorted(found.values(), key=lambda c: (c.__module__, c.__name__))


def emit(classes: list[type[Seared]]) -> str:
    """Render a full ``.ts`` module for the given seared/message classes and everything they reference."""
    classes = _expand(classes)
    blocks: list[str] = [_HEADER.rstrip()]
    enums = _collect_enums(classes)
    if enums:
        blocks.append('\n'.join(render_enum(e) for e in enums))
    preludes = _collect_preludes(classes)
    if preludes:
        blocks.append('\n'.join(preludes))
    blocks.extend(render_interface(c) for c in classes)
    return '\n\n'.join(blocks) + '\n'


def generate(target: str) -> str:
    """Discover every ``@zeared``/``@seared`` class under ``target`` and emit a single TypeScript module."""
    return emit(collect(target))


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for ``python -m zeared.doc.typescript``."""
    parser = argparse.ArgumentParser(
        prog='python -m zeared.doc.typescript',
        description='Generate TypeScript types for @zeared message classes.',
    )
    parser.add_argument('target', help='module or package to introspect')
    parser.add_argument(
        '-o',
        '--output',
        help='write to this .ts file (default: stdout)',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='exit non-zero if --output is missing or stale (CI guard)',
    )
    args = parser.parse_args(argv)

    content = generate(args.target)

    if args.check:
        if not args.output:
            parser.error('--check requires --output')
        try:
            with Path(args.output).open(encoding='utf-8') as fh:
                existing = fh.read()
        except FileNotFoundError:
            print(f'{args.output}: missing (run without --check)', file=sys.stderr)
            return 1
        if existing != content:
            print(f'{args.output}: out of date — regenerate', file=sys.stderr)
            return 1
        return 0

    if args.output:
        with Path(args.output).open('w', encoding='utf-8') as fh:
            fh.write(content)
    else:
        sys.stdout.write(content)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
